name: Feature Request
description: Suggest a new feature or enhancement for greport
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for greport? Describe the feature and why it would be useful.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of greport does this relate to?
      options:
        - API (Rust backend)
        - Dashboard (Next.js frontend)
        - Database
        - Sync (GitHub data sync)
        - Docker / Deployment
        - CI / Build
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is this related to a frustration?
      placeholder: "I find it difficult to ..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature or change you would like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative approaches?
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or references that would help.
    validations:
      required: false
